### ISSUE TITLE
Unable to generate report using release archive file

### ISSUE THREAD

**Issue by pavel-moskovkin** [Tsovak/go-test-parser#6]
I have downloaded [latest](https://github.com/Tsovak/go-test-parser/releases/tag/v1.0.2) archive [file for Linux](https://github.com/Tsovak/go-test-parser/releases/download/v1.0.2/go-test-parser_v1.0.2_Linux_x86_64.tar.gz) and was unable to generate report using the binary file `go-test-parser`.

Run command:
`go-test-parser logs.log -o report`
Got output:
```
Error: stat /workdir/go-test-parser/go-test-parser/cmd/templates/report.tmpl.html: no such file or directory
Usage:
  ./go-test-parser <go test -json -v output> [flags]
...
```

Seems like that the unpacked binary requires an html template file anyway, though I am not intended to run command `go get github.com/tsovak/go-test-parser/...` and would like to use just a downloaded binary file.

Is it possible to solve this issue? Would be very nice to have an option to generate test report using single binary file. 

Thank you.

**Comment by Tsovak** [comment]
fixed
